#!/bin/sh

mgmtdir="/home/git/repo-management"
currpath=$(pwd)
urlpath=${currpath#/srv/kdegit/repositories/}

# Poking anongit mirrors to cause immediate update
for mirror in `cat $mgmtdir/config/enabled_anongits.cfg`; do
       mirror=$(dig +short $mirror)
       curl --connect-timeout 1 --max-time 1 --resolve anongit.kde.org:80:$mirror http://anongit.kde.org/updateRepo/$urlpath &>/dev/null
done

# Initiate remote server update
remote_update_url=$mgmtdir/repo-configs/remote-update/$urlpath
if [ -f $remote_update_url ]; then
    remoteurl=`cat $remote_update_url`
    python $mgmtdir/bin/update-repo-mirror.py $urlpath $remoteurl &> /dev/null &
fi

# Kickoff a Jenkins build....
jenkinsauth=`cat ${HOME}/jenkins-credentials`
cleanpath=${urlpath/\/-}
cleanpath=${cleanpath/.git/}
for ref; do
    updatedref=${ref#refs/heads/}
    if [[ "$updatedref" != "master" ]] && [[ "$updatedref" != "frameworks" ]]; then
        updatedref="stable"
    fi
    curl --connect-timeout 1 --max-time 1 "http://build.kde.org/job/${cleanpath}_${updatedref}/build?token=${jenkinsauth}-${cleanpath}&cause=Triggered%20by%20commit" 2>1 1>/dev/null
    curl --connect-timeout 1 --max-time 1 "http://build.kde.org/job/${cleanpath}_${updatedref}_qt5/build?token=${jenkinsauth}-${cleanpath}&cause=Triggered%20by%20commit" 2>1 1>/dev/null
done

# Update local information
git update-server-info
