#!/bin/bash

# Usage:    ssh git@host clone <repo1> <repo2>
#
# Forks repo1 to repo2.  You must have read permissions on repo1, and create
# ("C") permissions for repo2, which of course must not exist.
#
# A fork is functionally the same as cloning repo1 to a client and pushing it
# to a new repo2.  It's just a little more efficient, not just in network
# traffic but because it uses git clone's "-l" option to share the object
# store also, so it is likely to be almost instantaneous, regardless of how
# big the repo actually is.

# Adapted from the "fork" command from Gitolite.
# Modified to ensure the base path remains constant

die() { echo "$@" >&2; exit 1; }
usage() { perl -lne 'print substr($_, 2) if /^# Usage/../^$/' < $0; exit 1; }
[ -z "$1" ] && usage
[ "$1" = "-h" ] && usage
[ -z "$GL_USER" ] && die GL_USER not set

# ----------------------------------------------------------------------
from=$1; shift
to=$1; shift
[ -z "$to" ] && usage

gitolite access -q "$from" $GL_USER R any || die "'$from' does not exist or you are not allowed to read it"

dirup=".."
[[ "$from" =~ "${dirup}" ]] && die "You are not allowed to traverse to parent directories."
[[ "$to" =~ "${dirup}" ]] && die "You are not allowed to traverse to parent directories."

oldIFS=$IFS
IFS="/"
fromarray=( $from )
toarray=( $to )
IFS=$oldIFS

if [ ${#toarray[@]} -gt 1 ]; then
    die "The destination takes a single path element -- the name. The location is chosen automatically."
fi

if [ ${#fromarray[@]} -eq 1 ]; then
    to="clones/$from/$GL_USER/$to"
elif [[ ${fromarray[0]} == "scratch" ]]; then
    if [ ${#fromarray[@]} -ne 3 ]; then
        die "Incorrect source location."
    fi
    from="scratch/${fromarray[1]}/${fromarray[2]}"
    to="scratch/$GL_USER/$to"
elif [[ ${fromarray[0]} == "clones" ]]; then
    from="clones/${fromarray[1]}/${fromarray[2]}/${fromarray[3]}"
    to="clones/${fromarray[1]}/$GL_USER/$to"
elif [[ ${fromarray[0]} == "websites" ]]; then
    from="websites/${fromarray[1]}"
    to="clones/websites/${fromarray[1]}/$GL_USER/$to"
else
    die "Not valid source/destination locations"
fi

# ----------------------------------------------------------------------
# IMPORTANT NOTE: checking whether someone can create a repo is done as above.
# However, make sure that the env var GL_USER is set, and that too to the same
# value as arg-2 of the access command), otherwise it won't work.

# Ideally, you'll leave such code to me.  There's a reason ^C is not listed in
# the help message for 'gitolite access'.
# ----------------------------------------------------------------------

echo "Cloning, please be patient..."

# clone $from to $to
git clone --bare -l $GL_REPO_BASE/$from.git $GL_REPO_BASE/$to.git
[ $? -ne 0 ] && exit 1

echo "$from forked to $to" >&2

# fix up creator, default role permissions (gl-perms), and hooks
cd $GL_REPO_BASE/$to.git
echo $GL_USER > gl-creator

touch gl-perms
if gitolite query-rc -q DEFAULT_ROLE_PERMS
then
      gitolite query-rc DEFAULT_ROLE_PERMS > gl-perms
fi

ln -sf `gitolite query-rc GL_ADMIN_BASE`/hooks/common/* hooks

# record where you came from
echo "$from" > gl-forked-from

# KDE changes
git config gitweb.owner "$GL_USER"
touch git-daemon-export-ok
echo "$from" > kde-cloned-from
echo "" > description

# trigger post_create
gitolite trigger POST_CREATE $to $GL_USER fork

# Make sure hooks are propagated
gitolite setup --hooks-only

# Trigger an initial sync to the anongit system
hooks/post-update
